# Ubuntu 風格的 Powerlevel10k 配置
# 將此內容保存到 ~/.p10k.zsh

# 主要顏色定義
typeset -g POWERLEVEL9K_BACKGROUND='#300A24'  # Ubuntu 終端背景色
typeset -g POWERLEVEL9K_FOREGROUND='#FFFFFF'  # 白色文字

# 提示符元素
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon                 # Ubuntu 標誌
  dir                     # 當前目錄
  vcs                     # git 狀態
  prompt_char             # 提示符
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status                  # 上一個命令的退出狀態
  command_execution_time  # 命令執行時間
  background_jobs         # 後台任務
  time                    # 當前時間
)

# Ubuntu 標誌設置
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='󱄛'
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#E95420'
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#300A24'

# 目錄設置
typeset -g POWERLEVEL9K_DIR_BACKGROUND='#300A24'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#E95420'
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_last'
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

# Git 設置
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#300A24'
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#4CBB17'
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#300A24'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#FFFF00'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#300A24'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#FF0000'

# 提示符設置
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#E95420'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#FF0000'

# 時間設置
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#300A24'
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#E95420'
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

# 命令執行時間
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='#300A24'
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#FFFF00'

# 狀態
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND='#300A24'
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#4CBB17'
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#300A24'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#FF0000'

# 其他設置
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

